// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtr7FQnrzbvJQ2jYv7R_4LHTFxwmfwBGY',
    appId: '1:524446986620:web:31bf44b39202060897b4f9',
    messagingSenderId: '524446986620',
    projectId: 'chatapptute-902a1',
    authDomain: 'chatapptute-902a1.firebaseapp.com',
    databaseURL: 'https://chatapptute-902a1-default-rtdb.firebaseio.com',
    storageBucket: 'chatapptute-902a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj34As98l4oGO_Q4Qhzu504wTuFxnJPjk',
    appId: '1:524446986620:android:4c90b14e4e56710c97b4f9',
    messagingSenderId: '524446986620',
    projectId: 'chatapptute-902a1',
    databaseURL: 'https://chatapptute-902a1-default-rtdb.firebaseio.com',
    storageBucket: 'chatapptute-902a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo0E_8JN9X7LalQqlz6bap4KPzh0KkRM0',
    appId: '1:524446986620:ios:c13beaced3af403597b4f9',
    messagingSenderId: '524446986620',
    projectId: 'chatapptute-902a1',
    databaseURL: 'https://chatapptute-902a1-default-rtdb.firebaseio.com',
    storageBucket: 'chatapptute-902a1.appspot.com',
    iosBundleId: 'com.example.flutterTaskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo0E_8JN9X7LalQqlz6bap4KPzh0KkRM0',
    appId: '1:524446986620:ios:bb70e4349f2f259697b4f9',
    messagingSenderId: '524446986620',
    projectId: 'chatapptute-902a1',
    databaseURL: 'https://chatapptute-902a1-default-rtdb.firebaseio.com',
    storageBucket: 'chatapptute-902a1.appspot.com',
    iosBundleId: 'com.example.flutterTaskManagementApp.RunnerTests',
  );
}
